name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Please check existing issues for before raising the issue. Thank you for your time and patience.'
        pr-message: ' Please raise PR with short and simple explaination. Thank you for contributing. We will get back to you soon.'
